### ISSUE TITLE
Error opening a TLS connection

### ISSUE THREAD

**Issue by yepMad** [amazonlinux/amazon-linux-2023#415]
**Describe the bug**
I upgraded from an Amazon Linux 2 with NodeJS 16 to Amazon Linux 2023 with NodeJS 18. Locally everything is fine. But on EC2, when Prisma tries to query the RDS database I get a TSL error. Something in mind?

**To Reproduce**
Try to use Amazon Linux 2023 ARM64 AMI with NodeJS 18 and Prisma

**Expected behavior**
Query gets success

**Additional context**
```
2023-08-13T18:17:15.315-03:00    Aug 13 21:17:14 ip-10-0-5-32 web[29143]: PrismaClientKnownRequestError:

2023-08-13T18:17:15.315-03:00    Aug 13 21:17:14 ip-10-0-5-32 web[29143]: Invalid `prisma.course.findFirst()` invocation:

2023-08-13T18:17:15.315-03:00    Aug 13 21:17:14 ip-10-0-5-32 web[29143]: Error opening a TLS connection: error:0A000127:SSL routines:tls_construct_ctos_supported_groups:no suitable groups:ssl/statem/extensions_clnt.c:238:No groups enabled for max supported SSL/TLS version

2023-08-13T18:17:15.315-03:00    Aug 13 21:17:14 ip-10-0-5-32 web[29143]: at Hr.handleRequestError (/var/app/current/prisma/generated/postgres/runtime/library.js:122:6999)

2023-08-13T18:17:15.315-03:00    Aug 13 21:17:14 ip-10-0-5-32 web[29143]: at Hr.handleAndLogRequestError (/var/app/current/prisma/generated/postgres/runtime/library.js:122:6388)

2023-08-13T18:17:15.315-03:00    Aug 13 21:17:14 ip-10-0-5-32 web[29143]: at Hr.request (/var/app/current/prisma/generated/postgres/runtime/library.js:122:6108)

2023-08-13T18:17:15.315-03:00    Aug 13 21:17:14 ip-10-0-5-32 web[29143]: at async l (/var/app/current/prisma/generated/postgres/runtime/library.js:126:10298)

2023-08-13T18:17:15.315-03:00    Aug 13 21:17:14 ip-10-0-5-32 web[29143]: at async HealthService.tryDbConnection (/var/app/current/dist/modules/health/health.service.js:20:9)

2023-08-13T18:17:15.315-03:00    Aug 13 21:17:14 ip-10-0-5-32 web[29143]: at async HealthController.check (/var/app/current/dist/modules/health/health.controller.js:22:9) {

2023-08-13T18:17:15.315-03:00    Aug 13 21:17:14 ip-10-0-5-32 web[29143]: code: 'P1011',

2023-08-13T18:17:15.315-03:00    Aug 13 21:17:14 ip-10-0-5-32 web[29143]: clientVersion: '5.1.1',

2023-08-13T18:17:15.315-03:00    Aug 13 21:17:14 ip-10-0-5-32 web[29143]: meta: {

2023-08-13T18:17:15.315-03:00    Aug 13 21:17:14 ip-10-0-5-32 web[29143]: message: 'error:0A000127:SSL routines:tls_construct_ctos_supported_groups:no suitable groups:ssl/statem/extensions_clnt.c:238:No groups enabled for max supported SSL/TLS version'

2023-08-13T18:17:15.315-03:00    Aug 13 21:17:14 ip-10-0-5-32 web[29143]: }

2023-08-13T18:17:20.044-03:00    Aug 13 21:17:14 ip-10-0-5-32 web[29143]: }

2023-08-13T18:23:07.192-03:00    Aug 13 21:23:02 ip-10-0-5-32 web[29143]: malloc(): unaligned fastbin chunk detected

2023-08-13T18:24:26.939-03:00    Aug 13 21:24:26 ip-10-0-5-32 web[29129]: error Command failed with signal "SIGABRT".

2023-08-13T18:24:28.192-03:00    Aug 13 21:24:26 ip-10-0-5-32 web[29129]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

2023-08-13T18:24:28.192-03:00    Aug 13 21:24:27 ip-10-0-5-32 web[29624]: yarn run v1.23.0-20220118.1001

2023-08-13T18:24:32.192-03:00    Aug 13 21:24:27 ip-10-0-5-32 web[29624]: $ node dist/main
```

**Comment by yepMad** [comment]
Closing... It's related to Prisma: https://github.com/prisma/prisma/issues/19743
